#!/bin/bash

set -xe

timedatectl set-timezone "Asia/Shanghai"

# setup hosts kojihub
echo "127.0.0.1 kojihub" >> /etc/hosts


# koji cli
#cp -a cli/koji /usr/bin/koji
#cp -a cli/koji.conf /etc/koji.conf 

#rm -rf /usr/lib/python3.6/site-packages/koji_cli
#cp -a cli/koji_cli  /usr/lib/python3.6/site-packages/

#rm -rf  /usr/lib/python3.6/site-packages/koji/
#cp -a koji  /usr/lib/python3.6/site-packages/

# koji hub
#/etc/httpd/conf.d/kojihub.conf
#/etc/koji-hub
#/etc/koji-hub/hub.conf
#/etc/koji-hub/hub.conf.d
#/usr/lib/systemd/system/koji-sweep-db.service
#/usr/lib/systemd/system/koji-sweep-db.timer
#/usr/sbin/koji-sweep-db

# cp -a hub/httpd.conf /etc/httpd/conf.d/kojihub.conf
# mkdir -p /etc/koji-hub/hub.conf.d || true
# cp -a hub/kojixmlrpc.py /usr/share/koji-hub/kojixmlrpc.py
# cp -a hub/kojihub.py /usr/share/koji-hub/kojihub.py
# cp -a hub/__init__.py /usr/share/koji-hub/__init__.py

# mkdir -p /mnt/koji || true
# cp -a hub/hub.conf /etc/koji-hub/hub.conf -a


# kojira
# mkdir /etc/kojira || true
# cp -a util/kojira.conf /etc/kojira/kojira.conf
# cp -a util/kojira /usr/sbin/kojira
# chmod +x /usr/sbin/kojira
# cp -a util/kojira.service /usr/lib/systemd/system/kojira.service
# systemctl daemon-reload
#systemctl restart kojira


# kojid
# cp -a builder/kojid /usr/sbin/kojid
# chmod +x /usr/sbin/kojid
# mkdir /etc/kojid || true
# cp -a builder/kojid.conf /etc/kojid/kojid.conf
# cp -a builder/kojid.service /usr/lib/systemd/system/kojid.service
# systemctl daemon-reload
# systemctl restart kojid


# kojiweb
# mkdir /etc/kojiweb || true
# cp www/conf/web.conf  /etc/kojiweb/web.conf
# mkdir -p /etc/httpd/conf.d/ || true
# mkdir -p /etc/kojiweb/web.conf.d/ || true
# cp www/conf/kojiweb.conf /etc/httpd/conf.d/kojiweb.conf

# rm -rf /usr/share/koji-web || true
# mkdir /usr/share/koji-web -p || true

# cp -a www/kojiweb /usr/share/koji-web/scripts
# cp -a www/lib /usr/share/koji-web/lib
# cp -a www/static /usr/share/koji-web/static


systemctl daemon-reload

# disable firewalld
systemctl disable --now firewalld &> /dev/null || true
setenforce 0 || true

# pki
cd /etc/koji-pki && chmod +x *.sh && ./9.onekey.sh


# setup sql
su - postgres -c "/usr/bin/postgresql-setup --initdb"
cat /etc/kojiweb/postgresql.conf > /var/lib/pgsql/data/postgresql.conf
cat /etc/kojiweb/pg_hba.conf > /var/lib/pgsql/data/pg_hba.conf
sync
systemctl enable --now postgresql.service
su - postgres -c "createuser koji"
su - postgres -c "createdb -O koji koji"
su - koji -c "psql koji koji < /usr/share/doc/koji/docs/schema.sql"
su - postgres -c '/usr/bin/pg_ctl reload -D /var/lib/pgsql/data'
# su - postgres -c '/usr/bin/pg_ctl restart -D /var/lib/pgsql/data'
cat > /etc/kojiweb/koji.sql << EOF
insert into users (id, name, password, status, usertype) values (999, 'kojiadmin', '', 0, 0);
insert into user_perms (user_id, perm_id,creator_id) values (999, 1, 999);
\d
select * from user_perms;
select * from users;
EOF
su - koji -c "psql koji koji < /etc/kojiweb/koji.sql"

# modify koji-theme
if [ -f /usr/share/koji-web/static/themes/rocky/include/header.chtml ]
then
    cp -a /usr/share/koji-web/static/themes/rocky/include/header.chtml /usr/share/koji-web/scripts/includes/header.chtml
fi

# add host/user
systemctl enable --now httpd.service
koji add-host kojibuilder1 i386 x86_64
koji add-host kojibuilder2 i386 x86_64
koji add-host kojibuilder3 i386 x86_64
koji add-host kojibuilder4 i386 x86_64
koji add-host kojibuilder5 i386 x86_64
su - koji -c "psql koji koji -c 'select * from users;'"
su - koji -c "psql koji koji -c 'select * from host;'"

# koji配置
koji add-user kojira
koji grant-permission repo kojira
koji add-host-to-channel kojibuilder1 createrepo 


# dir
mkdir -p /mnt/koji/{packages,repos,work,scratch}
chown -R apache.apache /mnt/koji

systemctl enable --now kojira.service
systemctl enable --now kojid.service

cat >> ~/.bashrc << EOF
# github.com/yifengyou/bash
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias l.='ls -d .* -a --color=auto'
alias ll='ls -l -h -a --color=auto'
alias ls='ls -a --color=auto'
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'
alias xzegrep='xzegrep --color=auto'
alias xzfgrep='xzfgrep --color=auto'
alias xzgrep='xzgrep --color=auto'
alias zegrep='zegrep --color=auto'
alias zfgrep='zfgrep --color=auto'
alias zgrep='zgrep --color=auto'
alias push='git push'


# History setting
export PROMPT_COMMAND="history -a"
export HISTTIMEFORMAT="%F %T "
export HISTSIZE=10000

# Proxy settings
#export http_proxy='127.0.0.1:5050'
#export https_proxy='127.0.0.1:5050'
#export ftp_proxy='127.0.0.1:5050'

#export http_proxy=
#export https_proxy=
#export ftp_proxy=

PS1='\[\e[32;1m\][\[\e[31;1m\]\u\[\e[33;1m\]@\[\e[35;1m\]\h\[\e[36;1m\] \w\[\e[32;1m\]]\[\e[37;1m\]\\\$\[\e[0m\] '
EOF
cp ~/.bashrc /home/koji/.bashrc

echo "All  done!"
