#!/bin/bash

function status () {
    for name in $@; do \
      echo ${name} $(systemctl is-active ${name}) $(systemctl is-enabled ${name}); \
      done | column -t | grep --color=always '\(disabled\|inactive\|$\)'
}

netstat -anpt |grep 80
netstat -anpt |grep 5432

for srv in `cat /etc/service.koji`
do
    status $srv
done

su - koji -c 'psql koji koji -c '\''select * from users;'\'''
su - koji -c 'psql koji koji -c '\''select * from user_perms;'\'''

koji hello

echo ""
echo "All done! All ok! Enjoy ~~~"